### PR TITLE
Fix font creation crash

### LINKED ISSUE #2226: linux - OpenToonz won't start - TFontCreationError
Some recent changes broke it, I had a working build from august 4, today I did a repository pull, installed and ...

    (gdb) r
    Starting program: /opt/opentoonz/bin/OpenToonz_1.2 
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7fffe79dd700 (LWP 14937)]
    [New Thread 0x7fffe4ade700 (LWP 14939)]
    [New Thread 0x7fffdfce9700 (LWP 14942)]
    plugin search directory:/home/alex/.config/OpenToonz/stuff/plugins
    walkDirectory_: /home/alex/.config/OpenToonz/stuff/plugins
    ===== PluginLoadController::finished() =====
    [Thread 0x7fffdfce9700 (LWP 14942) exited]
    [New Thread 0x7fffdfce9700 (LWP 14943)]
    plugin search directory:/home/alex/.config/OpenToonz/stuff/plugins
    walkDictionary: /home/alex/.config/OpenToonz/stuff/plugins [dry]
    QFileSystemWatcher::addPath: path is empty
    inotify_add_watch("/home/alex/.config/OpenToonz/stuff/projects/library") failed: "No such file or directory"
    [New Thread 0x7fffdf47d700 (LWP 14944)]
    [New Thread 0x7fffdec7c700 (LWP 14955)]
    terminate called after throwing an instance of 'TFontCreationError'
    
    Thread 1 "OpenToonz_1.2" received signal SIGABRT, Aborted.
    __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
    51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    (gdb) bt
    #0  0x00007ffff2ad3f3b in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
    #1  0x00007ffff2ad52f1 in __GI_abort () at abort.c:79
    #2  0x00007ffff7e90943 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #3  0x00007ffff7e96896 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #4  0x00007ffff7e968d1 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #5  0x00007ffff7e96b04 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #6  0x00007ffff586569c in TFontManager::setFamily(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >) (this=0x7ffff5b22fa8 <TFontManager::instance()::theManager>, family=...) at /usr/include/c++/8/ext/new_allocator.h:86
    #7  0x00005555557737cf in main (argc=<optimized out>, argv=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:1384
    #8  0x00007ffff2ac0b17 in __libc_start_main (main=
        0x555555770760 <main>, argc=1, argv=0x7fffffffe278, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe268) at ../csu/libc-start.c:310
    #9  0x000055555579c09a in _start () at ./toonz/sources/toonz/main.cpp:194

### PR DESCRIPTION
**Pull request by manongjohn**
This PR fixes #2226 

When starting up OT, it crashes if the preferred font is not a valid font for the system.  This fix should cause OT to start with whatever system default font is available.

### CODE REVIEW

File: toonz/sources/toonz/preferencespopup.cpp [hunk 1]
```diff
@@ -359,10 +359,15 @@ void PreferencesPopup::onDropdownShortcutsCycleOptionsChanged(int index) {
 void PreferencesPopup::rebuilldFontStyleList() {
   TFontManager *instance = TFontManager::instance();
   std::vector<std::wstring> typefaces;
-  QString font = m_interfaceFont->currentText();
-  instance->loadFontNames();
-  instance->setFamily(font.toStdWString());
-  instance->getAllTypefaces(typefaces);
+  QString font  = m_interfaceFont->currentText();
+  QString style = m_interfaceFontStyle->currentText();
```
Comment (shun-iwasawa) [inline toonz/sources/toonz/preferencespopup.cpp]: Is this variable `style` used in somewhere?

Comment (manongjohn) [reply toonz/sources/toonz/preferencespopup.cpp]: Originally I was going to populate `typefaces` with this value if  a TFontCreationError was caught, but decided to just leave it blank and forgot to remove the variable. It can be removed.

Comment (manongjohn) [reply toonz/sources/toonz/preferencespopup.cpp]: On second thought, I will populate it with the prefered font style even if it is invalid.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by manongjohn** [comment]
@shun-iwasawa Can you please finish reviewing this and merge so Linux builds wont have this issue anymore?  Thanks.

**Comment by shun-iwasawa** [comment]
@manongjohn  Sorry for keeping you waiting. Thank you for the fix ! LGTM
