### PR TITLE
Fix high dpi multimonitor glitch

### LINKED ISSUE #3687: visual bug
**Describe the bug**
The picture appears to be out of the white lined box

**To Reproduce**
List steps to reproduce the behavior.
1.I got a new computer with the new graphics card
2.i downloaded my files from my old laptop
3.I looked at them in opentoonz
4.and they were all out of the white box

**Expected behavior**
the picture binning in the right spot

**Screenshots**
image

**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 3070]
 - GPU Driver Version: [e.g. idk at the moment I will check]

### PR DESCRIPTION
**Pull request by shun-iwasawa**
**This PR needs to be checked carefully if it won't slows the performance.**

This PR fixes #3687 , the long-long-time bug with working on the multi monitor environment with different device-pixel ratio.
Now the device pixel ratio will be obtained from the screen where the widget is located.

### CODE REVIEW

**Comment by manongjohn** [comment]
It's funny....I recently got a new laptop/tablet with a 4K screen and my external tablet is HD so I was having that multiple monitor issue and was literally just about to look into it.  Seems you got to it first and likely have done a better job at identifying and fixing it than I would have. :)

I did test it and it seems to work well, even when moving OT from screen to screen with both pen and mouse.  Generally, performance for me seemed ok/normal though other user input is probably best.

The only real issue I have found so far is when drawing on a Raster level, not matter what color or style I choose, it always draw in black.  It was not doing this in a 2/26 nightly that I was using for comparison.

I did have some odd random pen behaviors but might have been my tablet acting goofy.

**Comment by RodneyBaker** [comment]
@manongjohn That issue of always drawing in black no matter what color style is chosen is something regularly seen in the github action artifacts.  I wasn't able to figure out why but have observed that those builds are the only source of the problem for me as of this date.

**Comment by artisteacher** [comment]
I'm using a mac & iPad (+ pencil) as an extended display (using Sidecar). I usually keep the main program window open on my mac & drag over a combo viewer to the iPad. 

If I change rooms on the mac, I end up with significant drawing offset on the iPad's combo viewer. If I don't change rooms on the mac, there's no offset on the iPad.

I can't select/move nodes in the schematic. The pan/select/zoom tools in the schematic have no impact.

I have some touch gesture issues, though I don't know if it's related to the multi monitor issue or if they are specific to a mac and/or iPad setup. On the iPad, two-finger pan triggers zooming instead. Two-finger pinch to zoom gets stuck zooming along the diagonal when first trying to zoom. Using the gesture to zoom on the touchpad seems to work normally and afterwards the zoom gesture works as expected on the iPad. Two finger tap doesn't reset the view on the iPad.

I don't have an issue with how the color displays.

**Comment by RodneyBaker** [comment]
I don't think I can adequately test high DPI monitors as I don't have the required hardware so... @manongjohn @artisteacher  Thanks for any and all feedback you can supply on the updates to this PR.

**Comment by manongjohn** [comment]
Playing with it a bit more on Win10 w/ XP-Pen tablet:
- I cannot replicate the issues artisteacher is experiencing on the mac w/ ipad.  Touch screen on my laptop-tablet appears to work fine for me. My external tablet doesn't have touch capabilities.

- All Stage Schematic icons are not scaling properly when moved to lower res tablet

image

- On Fx Schematic, just the Preview & Camera stand button icons are not scaling properly when moved to lower res tablet

- If my tablet is off and I start OT, if I turn on my tablet and drag OT into it, the drawings are offset again.   Closing OT and restarting it with the tablet on fixes it.

**Comment by artisteacher** [comment]
I haven't had a chance to test the new updates yet, but will try to soon.

Some of the issues I've had might be Linux/Mac specific - not just Mac/ipad specific. In the Google Groups, Mac users with Cintiqs have reported similar problems with the schematic & drawing offset.
https://github.com/opentoonz/opentoonz/issues/4219
https://github.com/opentoonz/opentoonz/issues/4154

**Comment by artisteacher** [comment]
I'm not sure if this was happening before, but "Creating Main Window" on opening is particularly slow. Everything else is the same as my last review.

**Comment by shun-iwasawa** [comment]
Thank you @manongjohn @artisteacher for testing !
Fixed the wrong pixmap scaling in Schematic.

@manongjohn 
>If my tablet is off and I start OT, if I turn on my tablet and drag OT into it, the drawings are offset again. Closing OT and restarting it with the tablet on fixes it.

Currently I made OT to check the device pixel ratios in all monitors once, and if all the monitors have the same device pixel ratio at the forefront, OT just use the static value without checking the current belonging screen of the widget throughout the session.

@artisteacher 
Thank you for testing with the mac & iPad configuration.
Regarding the reported problems, are they regressions due to this PR, or pre-existing ones which seem to be not resolved by this PR?

**Comment by artisteacher** [comment]
They were pre-existing - except for the excessively slow open, but I had hoped the PR would help.

Here's a video showing what happens in the combo viewer on the iPad after I've changed rooms. The offset has started glitching out, which I hadn't noticed before:

https://user-images.githubusercontent.com/21159116/156864984-801b00a7-054c-4ff3-a82f-a05f85bdd0a5.mov

**Comment by shun-iwasawa** [comment]
I tried with my MacBook Pro (w/ retina display) + secondary monitor (w/ normal dpi) configuration and confirmed that the original issue (the position offset glitch) seems to be resolved.
I think the mac & iPad issue should be handled separately and this PR is ready to be merged.

**Comment by artisteacher** [comment]
K, though I'd say it's more a secondary touchscreen monitor issue rather than just Mac+ipad. Linux/Mac+Cintiqs have some of the same issues.

Just to let you know, opening with low resolution on the current release allows me to change rooms without getting offset on the iPad. Though that's not an option on the latest MacOS.

**Comment by manongjohn** [comment]
Not sure if this is somehow related to what @artisteacher is experiencing...

I had the main window on my low res tablet, but dragged a Combo Viewer to my high res laptop/tablet.  When I draw in the either window, it was ok on the Combo Viewer until I switched rooms.  From that point forward the Combo Viewer was offset, however it wasn't quite offset to before this fix.   My toonz raster canvas was now positions down and to the left of camera.  Position wise, the drawings were appearing around camera center but scale was wrong.

I could fix it by resizing the Combo Viewer or drag the combo viewer back to high res and back to low res monitor (which essentially caused the combo viewer to resize)

**Comment by manongjohn** [comment]
Actually the combobox issue scenario happens when I have both windows in the high res monitor while my lower res tablet is on.

I seems to so this with undocked viewers

**Comment by artisteacher** [comment]
This does seem to be the same as my offset issue.

File: toonz/sources/toonzqt/fxschematicnode.cpp [hunk 1]
```diff
@@ -1239,22 +1239,20 @@ void FxSchematicPort::paint(QPainter *painter,
                             const QStyleOptionGraphicsItem *option,
                             QWidget *widget) {
   if (m_isPassThrough && getLinkCount() > 0) return;
-
+  int devicePixelRatio = getDevicePixelRatio(widget);
```
Comment (manongjohn) [inline toonz/sources/toonzqt/fxschematicnode.cpp:1242]: @shun-iwasawa 

FYI, when compiled on QT < 5.14, this line leads to a crash further down when painting the Fx Schematic's Output parent port.  Crash only occurs when the Fx Schematic is shown for the 1st time on the second low res monitor but the main monitor is high res.

As you are not using devicePixelRatio anywhere in this procedure, I verified it can be safely removed.
