### PR TITLE
Fix OSX menu roles

### LINKED ISSUE #534: No preferences window with french interface of opentoonz 1.0.3
Hello,

With the french interface of opentoonz 1.0.3, I can't open the preferences window.
capture d ecran 2016-06-27 a 22 34 25
when i click many times on "preferences".
capture d ecran 2016-06-27 a 22 36 35

The only way to have the preference window is to restart opentoonz and click on "preferences". during the start-up of opentoonz.
capture d ecran 2016-06-27 a 22 47 31

On mac OS X 10.10.5

Thank you all

(sorry i don't speak english very well).

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35541594-no-preferences-window-with-french-interface-of-opentoonz-1-0-3?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by artisteacher**
This fixes #534 and any other potential translation issues for menu items with OS X. 

Any menu items with certain keywords can override the About, Preferences, or Quit item due to naming conventions/behaviors in OS X.   Instead of adding "NoRole" to each problem menu item as it is found, this adds "NoRole" to all menu items. The menu items all stay in position as a result. Then the About, Preferences, and Quit menu items are assigned their correct role & will be placed per Mac conventions. This should prevent any hard to predict translation issues or potential problems with new menu items.

### CODE REVIEW

File: toonz/sources/toonz/mainwindow.cpp [hunk 1]
```diff
@@ -1418,14 +1418,23 @@ QAction *MainWindow::createAction(const char *id, const QString &name,
   QAction *action = new DVAction(name, this);
   addAction(action);
 #ifdef MACOSX
+// To prevent the wrong menu items (due to MacOS menu naming conventions), from
+// taking Preferences, Quit, or About roles (sometimes happens unexpectedly in
+// translations) - all menu items should have "NoRole"
+  if (MenuFileCommandType || MenuEditCommandType || MenuScanCleanupCommandType
+      || MenuLevelCommandType || MenuXsheetCommandType || MenuCellsCommandType || 
+      MenuViewCommandType || MenuWindowsCommandType) {
```
Comment (shun-iwasawa) [inline toonz/sources/toonz/mainwindow.cpp]: Thank you @artisteacher for tackling with the OSX issue !

It seems that this if statement condition will always be TRUE, since you don't compare any values and the type values listed here are all larger than zero.

How about rewriting lines 1424-1437 like as follows? : 

```
  if (strcmp(id, MI_Preferences) == 0)
    action->setMenuRole(QAction::PreferencesRole);
  else if (strcmp(id, MI_Quit) == 0)
    action->setMenuRole(QAction::QuitRole);
  else if (strcmp(id, MI_About) == 0)
    action->setMenuRole(QAction::AboutRole);
  else
    action->setMenuRole(QAction::NoRole);
```
