### PR TITLE
Fix of Brush Tip Display

### LINKED ISSUE #1899: Sceneviewer doesn't track movements on intial startup
When I open a scene in OT, immediately switch to a vector tool like magnet then move around viewer without pressing anything, the magnet's circle doesn't move.  It begins moving only after I press anywhere in the viewer.  This happens with both mouse or pen.

Steps to reproduce:
1) Open a scene in OT
2) Click on Magnet Tool
     - The magnet circle appears in the middle of viewer
3) Move mouse/pointer into viewer without pressing anything and move around
     - The magnet circle remains in middle of viewer

- You can switch or use any other tool, like pinch, pump, iron or cutter tools where there is a visual cue and move into the viewer and it still won't track movement.

4) Press anywhere on viewer
     - The magnet circle (or whatever tool you are now on) now starts moving with pointer

It should be noted, that once you press anywhere on the viewer 1x, the issue goes away.  It's only in the initial loading of OT does this happen.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/56486556-sceneviewer-doesn-t-track-movements-on-intial-startup?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #1950: Toonz Raster Cursor Display Issue
With the latest nightly build and OS X 10.11.6, there is a new issue with the display of the brush cursor - but only for Toonz Raster levels. The cursor (the red circle) does not update properly and a trail of red fragments is left visible during the stroke. At the end of the stroke, the fragments remain visible indefinitely if the brush does not move. As soon as the brush moves or the frames change, they disappear. Also, is there a reason the cursor is so much larger than the maximum brush size?

tr brush dispay

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/58060899-toonz-raster-cursor-display-issue?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR fixes some problems regarding displaying and refreshing of the brush tip (= a red circle displayed when using Brush tool).

- Fixed #1950 . ( Hopefully it will work. Please note that I tested only on Windows yet and will remove `WIP` after checking on OSX. )
- Fixed #1899. A problem that the brush tip stuck at the center of the viewer and does not move along the cursor when the first use of the brush tool after launch. It will fix the similar problem in all other tools as well.
- Enhanced the brush tip response when moving the cursor without any mouse buttons being pressed.  ( I introduced partial GL update for `BrushTool::mouseMove()` as well. )

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by manongjohn** [comment]
@shun-iwasawa  Regarding the change you put in to fix the circle stuck at center at first launch, will that fix all the tools as well or only the brush? I had put in #1899 that explains this happens for any tool at first launch.

File: toonz/sources/toonz/sceneviewerevents.cpp [hunk 1]
```diff
@@ -1024,7 +1024,7 @@ bool SceneViewer::event(QEvent *e) {
   if (e->type() == QEvent::MouseButtonPress)
     clock.start();
   else if (e->type() == QEvent::MouseMove) {
-    if (clock.elapsed() < 10) {
+    if (clock.isValid() && clock.elapsed() < 10) {
```
Comment (shun-iwasawa) [inline toonz/sources/toonz/sceneviewerevents.cpp]: @manongjohn 

> Regarding the change you put in to fix the circle stuck at center at first launch, will that fix all the tools as well or only the brush?

The fix was done in here in `SceneViewer::event()` so yes, it will fix not only the brush tool but all the tools.
Thank you for letting know that. I'll update my comment.

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by masafumi-inoue** [comment]
LGTM

**Comment by blackwarthog** [comment]
Visual artifacts related with algorithm of function SceneViewer::GLInvalidateRect. This function remember only last passed rectangle instead of increasing invalidation rectangle.

I've fixed it in my branch feature09_assistants
https://github.com/blackwarthog/opentoonz/commit/fea06f266c550035d652f3cda827c54eb5d9ba48

**Comment by blackwarthog** [comment]
Oops! Sorry, my mistake. You actually done the same fix.

I've compared changes and found bug.
When we called SceneViewer::GLInvalidateAll() and SceneViewer::GLInvalidateRect() after that, then invalidation rectangle will reduced.
