### PR TITLE
Fix frame range undo

### LINKED ISSUE #1758: Crash  with Vector Brush in Frame Range mode (gif).
1. Create new Vector Level with some frames.
2. Move the frames down in Xsheet.
3. Use the Brush Tool with Frame Range option to create an animation.
4. If you try to undo the operation, the program will crash.

ezgif-2-20c5afdf1c

### PR DESCRIPTION
**Pull request by turtletooth**
Fixes #1758 

For some reason it was able to get the current level or frame id when it was trying to, so I passed it on from an earlier point.

### CODE REVIEW

File: toonz/sources/tnztools/brushtool.cpp [hunk 1]
```diff
@@ -358,9 +359,14 @@ static void addStroke(TTool::Application *application, const TVectorImageP &vi,
...
-  TXshSimpleLevel *sl = application->getCurrentLevel()->getSimpleLevel();
+  TXshSimpleLevel *sl;
+  if (!sLevel) {
+    sl = application->getCurrentLevel()->getSimpleLevel();
+  } else {
+    sl = sLevel;
+  }
   TFrameId id = application->getCurrentTool()->getTool()->getCurrentFid();
-
+  if (id == -2 && fid != -2) id = fid;
```
Comment (shun-iwasawa) [inline toonz/sources/tnztools/brushtool.cpp]: Confirmed this PR fixes the problem. Thank you !

How about using `TFrameId::NO_FRAME` instead of a magic number `-2` ?

**Comment by turtletooth** [comment]
Thanks @shun-iwasawa - I made the change.

File: toonz/sources/tnztools/brushtool.cpp [hunk 2]
```diff
@@ -422,10 +428,11 @@ namespace {
 
 void addStrokeToImage(TTool::Application *application, const TVectorImageP &vi,
                       TStroke *stroke, bool breakAngles, bool frameCreated,
-                      bool levelCreated) {
+                      bool levelCreated, TXshSimpleLevel *sLevel = NULL,
+                      TFrameId id = -2) {
```
Comment (shun-iwasawa) [inline toonz/sources/tnztools/brushtool.cpp]: @turtletooth Can you please modify here as well?

**Comment by turtletooth** [comment]
Sorry for missing that.  Got it.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
LGTM Thank you @turtletooth !
